const NavRoutes = {
  ONBOARD: 'OnBoard',
  LOGIN: 'Login',
  REGISTER: 'Register',
  OTP: 'Otp',
  FORGOT_PASSWORD: 'ForgotPassword',
  NEW_PASSWORD: 'NewPassword',
  HOME: 'Home',
  MENU: 'Menu',
  CART: 'Cart',
  ADDRESS: 'Address',
  ORDER_HISTORY: 'OrderHistory',
  TERMS: 'Terms',
  CONTACT_US: 'ContactUs',
  EDIT_PROFILE: 'EditProfile',
  NOTIFICATION: 'Notification',
  TRACK_ORDER: 'TrackOrder',
  PAYMENT: 'Payment',
  PAYMENT_WEB_VIEW: 'PaymentWebView',
  PAYMENT_SUCCESS: 'PaymentSuccess',
  ADDCARD: 'AddCard',
  SEARCH: 'Search',
  PRODUCT: 'Product',
};

export default NavRoutes;
